---

#-----------------------------------------------------------------------------+
# Description: Do something very important
#-----------------------------------------------------------------------------+
- name: xPLAY_1x
  # v------------------------------------------------------ ANSIBLE-PLAY-SETTINGS
  hosts: xHOST_FROM_INVENTORY_1x
  remote_user: xLINUX_USERx
  # ^------------------------------------------------------ ANSIBLE-PLAY-SETTINGS
  tasks:
   - name: xTASK_1x
     xANSIBLE.MODULEx: # Imagine we use [ansible.builtin.yum]
      name: xSERVICEx
      state: xLATESTx
  
   - name: xTASK_2x
     xANSIBLE.MODULEx: # Image we use [ansible.builtin.template]
       src: /xPATH/ON/THIS/PC/TO/FILE.j2x
       dest: /xPATH/ON/REMOTE/PC/TO/FILE.TXTx









#-----------------------------------------------------------------------------+
# Description: Do something very important
#-----------------------------------------------------------------------------+
- name: xPLAY_2x
  # v------------------------------------------------------ ANSIBLE-PLAY-SETTINGS
  hosts: xHOST_FROM_INVENTORY_1x
  # ^------------------------------------------------------ ANSIBLE-PLAY-SETTINGS
  tasks:
   - name: xTASK_3x
     xANSIBLE.MODULEx: # Imagine we use [ansible.builtin.yum]
      name: xSERVICEx
      state: xLATESTx